name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        working-directory: ./front
        run: npm install

      - name: Build
        working-directory: ./front
        run: |
          # For GitHub Pages, get the repository name to use as the base href
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          echo "Building with base-href=/$REPO_NAME/"
          npm run build -- --configuration production --base-href="/$REPO_NAME/"
          cp dist/catan/browser/index.html dist/catan/browser/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'front/dist/catan/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 