[package]
name = "catan-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-web = "4.4"
actix-web-actors = "4.2"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.4", features = ["v4", "serde"] }
env_logger = "0.10"
log = "0.4"
rand = "0.8"

[dev-dependencies]
actix-rt = "2.9"