# .github/workflows/shuttle-deploy.yml
name: Deploy Backend to Shuttle

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JB7KGM3SAK7HB5X5S0HZYH0K
          working-directory: 'back'
          allow-dirty: true